### ISSUE TITLE
Annotations seem to be enabled by default

### ISSUE THREAD

**Issue by kristojorg** [d-i-t-a/R2D2BC#146]
When I instantiate a reader using the following code:
```
    D2Reader.load({
      url: url,
      injectables: injectables,
    })
```

I get an error complaining about annotations:

```
TypeError: undefined is not an object (evaluating 'this.delegate.rights.enableAnnotations')
```

I can post the HTML I used if that's helpful, but it seems that annotations are assumed to be enabled even though I didn't explicitly ask for them? Just a guess

**Comment by aferditamuriqi** [comment]
This is fixed in 1.7.1
