### ISSUE TITLE
goTo using result.displayInfo.resourceScreenIndex

### ISSUE THREAD

**Issue by PekopT** [d-i-t-a/R2D2BC#191]
Hello! 

first off all, thanks for awesome work! 

I have a question: i'm trying to use your reader for my pet project for mobile devices.
I had disabled scroll view and use only paginated behaviour. 

is it possible to use goTo using result.displayInfo.resourceScreenIndex ?

**Comment by aferditamuriqi** [comment]
Hello @PekopT , sorry i just now saw your question here. 
The resourceScreenIndex is only used for the current resource as display info, not really for navigation. and also this info is only available for the current resource (chapter, spine..) Can you explain a bit more what exactly you are trying to do? I am sure I have an api in this reader that fits what you're looking for.

**Comment by PekopT** [comment]
got it. thanks!
