### ISSUE TITLE
nextPage goes to nextChapter in paginated view

### ISSUE THREAD

**Issue by kristojorg** [d-i-t-a/R2D2BC#198]
I am seeing an issue where the `nextPage` api is moving me to the next chapter while viewing a paginate reflowable book and not at the end of the chapter. The error seems to be stemming from here:

https://github.com/d-i-t-a/R2D2BC/blob/0928efe6aa6b02aad0c7667dc3bb22b20a9ddca0/src/views/ReflowableBookView.ts#L324

It appears that the `rightWidth` is 0 in my case. I'm not totally sure what the `rightWidth` is? Is it the amount of remaining chapter?

You can see this by running the example: `npm run example:reader-class` in my branch `fix/next-page` and then clicking next page a few times. It's always going by chapter

**Comment by kristojorg** [comment]
I looked in to it a bit more and it looks like there are no more columns positioned to the right of the one in view... it is just a single column, so that's why this is returning 0 in my case

**Comment by aferditamuriqi** [comment]
Found the issue here which is related to the html markup, there will be some changes that will improve how the markup is used currently, as such then allowing the reader container to be any size an be placed anywhere within an app

**Comment by aferditamuriqi** [comment]
like this one in full screen mode 

[full screen reader
<img width="1298" alt="Screen Shot 2021-06-28 at 5 17 17 PM" src="https://user-images.githubusercontent.com/17150623/123705264-b7e3f100-d834-11eb-9d8c-d29cbba22e40.png">
](https://www.dropbox.com/s/hv7jjhx6mp72qu4/fill%20view%20reader%20v2.mov?dl=0)

**Comment by kristojorg** [comment]
I figured out this was caused by me not importing the css properly, so it's resolved now. Thanks for your help!
