### ISSUE TITLE
Enable strictNullChecks

### ISSUE THREAD

**Issue by kristojorg** [d-i-t-a/R2D2BC#206]
This is going to be a relatively large piece of work, but the payoff will also be large. We should enable TS `strictNullChecks` so that TS will warn us when we are accessing a property on a possible `null` or `undefined` value, thus eliminated the most common class of JS errors.

**Comment by aferditamuriqi** [comment]
enabled strict null in this PR https://github.com/d-i-t-a/R2D2BC/pull/316
