### ISSUE TITLE
Is it possible to insert reader into part of page?

### ISSUE THREAD

**Issue by PekopT** [d-i-t-a/R2D2BC#212]
I'm trying to insert reader inside div that no use 100% of width 
is it possible ?

**Comment by PekopT** [comment]
@aferditamuriqi

**Comment by aferditamuriqi** [comment]
Hello @PekopT i see that is a valid use case to embed the reader within a portion of a site, a custom width should be already possible, but probably not a custom height. we didn't test that out, but we are currently working on a V2 version, and we will consider that option as well, so that the reader doesn't assume the full height.

**Comment by aferditamuriqi** [comment]
something like this will be possible in V2

[widget reader](https://www.dropbox.com/s/2fof034rd8bvprs/mini%20reader%20v2.mov?dl=0)

<img width="857" alt="Screen Shot 2021-06-28 at 4 53 06 PM" src="https://user-images.githubusercontent.com/17150623/123702631-5ff7bb00-d831-11eb-8711-bd8331299f45.png">

**Comment by PekopT** [comment]
@aferditamuriqi wow! That's really cool! 

Can you please provide an example for custom width in V1 ?

When will you release version 2 ?

**Comment by aferditamuriqi** [comment]
@PekopT here is one example:

```
    <div class="content" id="root" style="display: flex;flex-direction: row;" >
        <div style="position:fixed;top:0;left:0;z-index: 1000;bottom: 0; overflow: scroll;width: 200px;border: solid;">

            <button onclick="javascript:D2Reader.previousResource()">previous resource</button><br>
            <button onclick="javascript:D2Reader.nextResource()">next resource</button><br>
            <button onclick="javascript:D2Reader.previousPage()">previous page</button><br>
            <button onclick="javascript:D2Reader.nextPage()">next page</button><br>
            <button onclick="javascript:D2Reader.scroll(true)">scroll</button><br>
            <button onclick="javascript:D2Reader.scroll(false)">paginated</button><br>

        </div>
        <div id="D2Reader-Container" style="border: solid 5px rebeccapurple; width: 500px; padding: 30px; position: absolute;left: 220px;">
            <main style="overflow: hidden" id="iframe-wrapper">
                <div id="reader-loading" class="loading"></div>
                <div id="reader-error" class="error"></div>
            </main>
        </div>
    </div>
```


[v1 custom width](https://www.dropbox.com/s/vn5yjmxgunc5qjr/v1%20fixed%20width%20example.mov?dl=0)

you can adjust the `D2Reader-Container` style to fit within your site. the `main` you should not change, that might otherwise.

**Comment by PekopT** [comment]
@aferditamuriqi smth goes wrong 
![image](https://user-images.githubusercontent.com/1135374/124518961-9bc1f000-ddf0-11eb-8640-737f2a8b64ca.png)

**Comment by aferditamuriqi** [comment]
@PekopT i believe that's because of the 30px margin. try without that margin. 

the 2.0.0-alpha.1 is also available, it's still in alpha, but feel free to give it a try.

**Comment by aferditamuriqi** [comment]
@PekopT i am closing this ticket, as i think we covered the issues here. if anything else please reopen a new issue . thank you :)
