### ISSUE TITLE
V2 height issue 

### ISSUE THREAD

**Issue by PekopT** [d-i-t-a/R2D2BC#229]
https://brilliantov-screens.s3.eu-central-1.amazonaws.com/screencast_2021-07-12_00-27-45.mp4

something wrong with container height

**Comment by PekopT** [comment]
@aferditamuriqi

**Comment by aferditamuriqi** [comment]
@PekopT could you share you markup ? V2 is not entirely stable yet, especially not this container changes. But if you can share more info, we could look into it.

**Comment by aferditamuriqi** [comment]
Fixed in https://github.com/d-i-t-a/R2D2BC/pull/248
