### ISSUE TITLE
v2 resize font in paginated mode doesn't recalculate the number of pages of previously shown chapters

### ISSUE THREAD

**Issue by AntonOfTheWoods** [d-i-t-a/R2D2BC#267]
With current v2 (using the standard example epub, with index_dita.html), if you:

1. Show a chapter with a small font, 
2. Continue to the following chapter using the next button,
3. Increase (by a lot) the font size,
4. Return to the previous chapter using the previous button,

Then the number of pages is not correctly recalculated, and the previous chapter cuts off large segments at the end of the chapters.

The same procedure appears to correctly recalculate using v1.

**Comment by aferditamuriqi** [comment]
@AntonOfTheWoods the latest V2 beta version should not have this issue anymore. i just merged and published a new version, and tested this, and i can confirm screens are calculated correctly.
