### ISSUE TITLE
Paginated view text truncation in v2

### ISSUE THREAD

**Issue by AntonOfTheWoods** [d-i-t-a/R2D2BC#293]
The included Call of the Wild example demonstrates the phenomenon for me with the head of `v2` using the "Dita Example:". Both the "Dita Sample Read:" and "Material Example:" seem to be missing files (from `injectables`) and error out.

To reproduce, simply open the COTW link with the "Dita Example" link, switch to paginated view and carefully navigate forward until one of the chapters is truncated. On my screens this is within the first 3 or so chapters.

@kristojorg , this phenomenon is also visible using today's `main` of NYPL's web-reader.

**Comment by aferditamuriqi** [comment]
Should be fixed in https://github.com/d-i-t-a/R2D2BC/pull/306

**Comment by AntonOfTheWoods** [comment]
Thanks @aferditamuriqi ! Let's close this for now and I'll try and actually be useful if this issue comes back. I migrated back to v1 that has another issue for me but that I had a hack-around for (setting the fontsize triggers a recalculation, which was the only way I could get it to increase the size after my injectable runs and injects a heap more text into the chapters). I might not have the bandwidth to test the new v2 for a while.
