### ISSUE TITLE
isScrollMode sometimes is called too early

### ISSUE THREAD

**Issue by kristojorg** [d-i-t-a/R2D2BC#294]
I have been getting errors of "parent element is null" that seem to come from [this line](https://github.com/d-i-t-a/R2D2BC/blob/v2/src/views/ReflowableBookView.ts) in `ReflowableBookView`. It appears that `isScrollMode()` is called too early, and `this.iframe.contentDocument` is undefined. I made a patch for this to check if `this.iframe.contentDocument` is defined before trying to find the `html` element, but that probably won't fix the underlying problem.

My suggestion would be that we turn on `strictNullChecks` in typescript config and fix all the type errors resulting from that, as that will implicitly force us to deal with this.

**Comment by aferditamuriqi** [comment]
should be resolved in this PR https://github.com/d-i-t-a/R2D2BC/pull/306
