### ISSUE TITLE
Loading .opf manifest

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#392]
Hi, thanks for making this helpful toolkit. It has saved me a lot of time.
I wanted to load an .opf file since the source I have only has manifest files in .opf format.

The issue is that when I pass the url for an .opf manifest, I get the follow error:
![image](https://user-images.githubusercontent.com/22940567/195657702-2423b2e3-60aa-4349-9324-6d864bd2ee5c.png)
It looks like R2D2BC is trying to parse the json data but .opf files are in xml.
Is there a way I can load the .opf files directly?

**Comment by MuhammadPen** [comment]
Also I cant find any reference to what type of json structure r2d2bc needs. Up until now I was testing using the manifest available here:
https://alice.dita.digital/manifest.json

**Comment by MuhammadPen** [comment]
I've also tried converting my .opf xml file into json and using that as the manifest, but getting these warnings 
![image](https://user-images.githubusercontent.com/22940567/195677453-7e1ba824-4952-43bb-8ccf-381f76c5ff9b.png)
and the book does not load.
Looks like the structure that r2d2bc needs is different?

**Comment by aferditamuriqi** [comment]
Hello @MuhammadPen R2D2BC takes readium manifest as source. https://github.com/readium/webpub-manifest and you can take a look there how the manifest is structured, you can also take a look at the Readium Shared which does create from .epub files exploded epubs including it's manifests, R2D2BC does conforms to all readium architecture in terms of shared models etc. https://github.com/readium/r2-shared-js.

we do not just take the opf itself, you will need to process a manifest.

you can also run the samples included in this project, which uses the Readium Streamer and Readium Shared to process the epubs.

**Comment by MuhammadPen** [comment]
I used [epub-to-webpub](https://github.com/NYPL/ePub-to-webpub) to generate a compatible format for r2d2bc and it seems to the load epub contents. However now I have a different problem. Please check out #393
