### ISSUE TITLE
Loading from protected urls (firebase)

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#393]
Hi, I am trying to render an epub via r2d2bc. The issue is that all my files are hosted in firebase and the storage bucket is not public. Meaning that if I want to load the pages and content from firebase I need a token appended at the end of the urls that are listed in the manifest.
That much I can do via a function that appends an active token at the end of all urls before giving the manifest to r2d2bc. The real problem arises when there are embedded links/urls in the book that r2d2bc is trying to load. For example there is a file named `0.css` that is linked inside the book. When r2d2bc tries to load the book, it also tries to load this file, which causes a 404 error.
![Untitled](https://user-images.githubusercontent.com/22940567/196138237-daafe592-eba3-4a83-b8bd-6556da174569.png)

Is there any way I can load epubs from protected urls?

**Comment by aferditamuriqi** [comment]
You will need to generate the manifest then dynamically and append the token to the URLs in the manifest.
Or host a service in between that handles the urls.

**Comment by MuhammadPen** [comment]
I am successfully able to generate the manifest and append the token. The problem is with links inside the book itself, which I can not edit.
I have come across an approach of using service workers to intercept the http calls coming from the r2d2bc iframe and change the request url before sending the request. But I am uncertain. This seems like quite a work around. Is there no simple way to load epubs that are behind protected links? even if we have the access token?

**Comment by aferditamuriqi** [comment]
You can use the getContent API and manipulate urls or content in general

see example here 
https://github.com/d-i-t-a/R2D2BC/blob/dc2c3f6fd8854250ff549fe1e3c463bbf9b5a058/viewer/index_sampleread.html#L331

**Comment by MuhammadPen** [comment]
Hi @aferditamuriqi , it seems to me that `getContent` api only returns the url of the currently loaded resource. How can I use that to manipulate the content of the file?
![image](https://user-images.githubusercontent.com/22940567/196433743-89986eb3-7ff1-491f-b8d7-19286b278595.png)

![Untitled2](https://user-images.githubusercontent.com/22940567/196434008-e44a26d6-176e-4af7-86d2-8ba791c9568d.png)

**Comment by aferditamuriqi** [comment]
Well you get the current requested href and you manipulate what you need and return the content . Just debug it and you'll figure out

**Comment by aferditamuriqi** [comment]
in your screenshot you have changed the method signature to data and you are returning as any, which is incorrect, the resolve returns the value, based on the href you need to do the fetching manipulating etc. and resolve with the data. how you are trying to do it is not how this function with a promise return works

**Comment by MuhammadPen** [comment]
Thanks for the info. I fixed my syntax and now I am able to load the document properly. :)

![image](https://user-images.githubusercontent.com/22940567/196480096-04626362-81a5-4ab2-9348-47be7c30befb.png)

![image](https://user-images.githubusercontent.com/22940567/196480161-8c936a47-785d-4e52-b7fa-dc91ec802de9.png)
