### ISSUE TITLE
Inconsistent behavior from D2Reader.goTo() 

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#396]
I am trying to use the `goTo` function to navigate. However, it is inconsistent. Sometimes to goes to the correct location, other times it just says at the cover page. This is the code I am using:
![image](https://user-images.githubusercontent.com/22940567/200168548-cc97994e-05fa-42f0-828c-d98648d96121.png)

Maybe I am missing something?

**Comment by MuhammadPen** [comment]
it seems like calling `D2Reader.goTo` on a button click is consistent

**Comment by aferditamuriqi** [comment]
> it seems like calling `D2Reader.goTo` on a button click is consistent

Please provide more details of what you mean by inconsistent .

**Comment by MuhammadPen** [comment]
I think this was the issue with using the navigate function in a useEffect. I moved it out into a separate function and its working fine now. closing
