### ISSUE TITLE
navigation using cfi

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#400]
Hi, I see that the D2Reader has a `goTo` function which takes a `locator` object and uses it to navigate the reader. But there is a problem in this approach.
On different screen sizes, the value for progression changes. This makes it an unreliable way of sharing reader location with other users.

I was wondering if there is a way to navigate the reader using cfi, as a cfi value should be same for any given screen size.

**Comment by MuhammadPen** [comment]
`reader.goTo` takes in a `locator` argument which is described here:
![image](https://user-images.githubusercontent.com/22940567/203028783-6543b816-e962-4066-89b0-2f6a41337b65.png)
and the `Locations` type:
![image](https://user-images.githubusercontent.com/22940567/203028909-bd5eb3bc-e9ec-4983-9bd4-9d8dca71c4ce.png)
I see that there is a fragment identifier here. I have tried calling the `goTo` function with a generated cfi  from the `readium-cfi-js` library as a string in the fragment identifier, but it does not seem to work.
I simply want to create an annotation, get its cfi and then navigate the reader to that annotation using cfi.
Is there no simple way of achieving this?

**Comment by muhammadomarhashmi** [comment]
@MuhammadPen  R2D2BC uses a custom way to navigate using progression There is no way to navigate the reader using cfi unfortunately

**Comment by MuhammadPen** [comment]
> @MuhammadPen R2D2BC uses a custom way to navigate using progression There is no way to navigate the reader using cfi unfortunately

@aferditamuriqi this seems like quite a limitation. Is this correct?

Here is how I'm using the navigate function:
```
try {
      await reader?.goTo({
        href: pageName,
        locations: { fragment: fragment },
      });
    } catch (error) {
      console.error(error);
    }
```
Here is my fragment:
```epubcfi(/6/8!/4/2[pgepubid00003]/8/1:24)```

 Nothing happens when I call the above goTo method and I dont get any errors either.

**Comment by aferditamuriqi** [comment]
> @MuhammadPen  R2D2BC uses a custom way to navigate using progression There is no way to navigate the reader using cfi unfortunately

This is incorrect, R2D2BC does not use a custom way but the Readium way to navigate . It uses a locator and CFI is not part of R2 !

**Comment by MuhammadPen** [comment]
@aferditamuriqi Can you please explain what is the `fragment` property inside the locator? I though it was cfi, but as you said readium v2 does not support cfi. so what does this fragment identifier mean?
![image](https://user-images.githubusercontent.com/22940567/203705353-1002fe7b-712c-44c6-b629-b9e4e03835d9.png)
