### ISSUE TITLE
get visible contents from reader

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#403]
how can you get the contents of the starting and ending locator for content that is visible in the reader?
Lets say we have pagination enabled and our reader render's two pages. How can I get content of only the page that is visible.

Here's an example:
PAGE 1: 
![image](https://user-images.githubusercontent.com/22940567/204003102-17901d83-0af2-4d03-8ef1-e4fdc8f6fab8.png)
PAGE 2:
![image](https://user-images.githubusercontent.com/22940567/204003159-7c31d5fa-4819-4ebd-a207-a47308597ef6.png)
I want to get the html content of PAGE 1 ONLY. not of the entire chapter. How can I do that?

**Comment by MuhammadPen** [comment]
@aferditamuriqi

**Comment by aferditamuriqi** [comment]
Use setting as paginated and columns to 1

**Comment by MuhammadPen** [comment]
this is not what I meant. I want to get the text that is rendered in the first page inside javascript, not on screen.
I want to use this text to see what contents of the epub the user can currently see.
@aferditamuriqi

**Comment by aferditamuriqi** [comment]
That's not part of the features and ePub reader has .

You might es t to consider writing your own script and inject
