### ISSUE TITLE
accessing the underline reader

### ISSUE THREAD

**Issue by MuhammadPen** [d-i-t-a/R2D2BC#404]
Following up on #403 , I see that readium sdk has a function called `ReaderView.getFirstVisibleCfi()` as discussed [here](https://github.com/readium/readium-js-viewer/issues/609).
When I look into the source code for `r2d2bc` I dont see this function, so I assume that it was never exported.
However, r2d2bc is built on top of readium v2. So I was wondering if it was possible for me to access the underlying `ReaderView.getFirstVisibleCfi()` function from inside r2d2bc?

**Comment by MuhammadPen** [comment]
@aferditamuriqi

**Comment by aferditamuriqi** [comment]
R2D2BC is NOT. Built on top of Readium . It just follows some of the main architecture of R2. R2 does not support CFI either . 

Please stop trying to find CFI here . I’ve explained in other tickets that we are not supporting navigation via CFI. 
If you want to create a PR that supports that , we are happy to review . 

But no support for CFI is not a bug and should not reported as such .

Thanks for your understanding .
