### ISSUE TITLE
Slack invite link no longer active

### ISSUE THREAD

**Issue by mbenoni** [d-i-t-a/R2D2BC#424]
The link on the Slack badge in the README is no longer active. Could this be updated?

**Comment by mbenoni** [comment]
The same goes for other places the link is used, such as the CONTRIBUTING page.

**Comment by aferditamuriqi** [comment]
@mbenoni the link is still active, just double checked , can you provide more details what you see when trying the link?

**Comment by aferditamuriqi** [comment]
try this one and let me know if this works. https://join.slack.com/t/r2d2bc/shared_invite/zt-1n5c3bzlz-R3kOk0P_GtmuM~Il0yU7sg

**Comment by mbenoni** [comment]
The links lead to this page:

<img width="1840" alt="no-longer-active" src="https://user-images.githubusercontent.com/5700203/212855391-784e1521-eb4a-4d7a-b9c8-10c4300efd43.png">

I believe Slack invite links expire after 30 days by default, but that you can create a link that never expires.

The link you provided worked though, thanks!

**Comment by aferditamuriqi** [comment]
This has been resolved

**Comment by aferditamuriqi** [comment]
This has been resolved
