### ISSUE TITLE
npm audit alert

### ISSUE THREAD

**Issue by burninc0de** [d-i-t-a/R2D2BC#483]
```
Severity: critical
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883

node_modules/xmldom

15 vulnerabilities (9 moderate, 5 high, 1 critical)
```

I'm not really sure why this is happening. According to package.json the dependency is "@xmldom/xmldom": "^0.8.10" -- in this version the vulnerability is fixed, no?

EDIT: i am a node noob, so perhaps this is a dumb question. I really love what you've done with this project and would like to deploy R2DBC on live server, but I'm not sure if it's safe. would be grateful for any pointers. thanks

**Comment by aferditamuriqi** [comment]
@burninc0de thank you for your message, we keep the dependencies always up to date, i am sure that any of these will resolve in the next version. and as you can see we package new versions often.

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/d-i-t-a/R2D2BC/pull/395
