### ISSUE TITLE
event listener for unhandled clicks/touch?

### ISSUE THREAD

**Issue by gotson** [d-i-t-a/R2D2BC#627]
Hi,

is it possible to add an event listener for clicks or touch events that were not handled by the reader?

I would like to display my own menu when a click/touch event happens, so if such event happen, and is not acted upon by the reader itself, my callback would be called.

**Comment by aferditamuriqi** [comment]
you can do this by injecting your own script. see injectables.

**Comment by gotson** [comment]
> you can do this by injecting your own script. see injectables.

i am not sure how to use that, would you be able to provide some guidance or basic very simple example ? I only need some kind of callback for unhandled clicks, i will handle the menu display and everything outside the reader.

**Comment by aferditamuriqi** [comment]
@gotson there is a basic implementation of a click script in the injectables samples. look into the index_api.html and for the injectables section, there is for example an injectable like this

`            { type: 'script', url: '/viewer/injectables/click/click.js' },
`

**Comment by gotson** [comment]
> @gotson there is a basic implementation of a click script in the injectables samples. look into the index_api.html and for the injectables section, there is for example an injectable like this
> 
> ` { type: 'script', url: '/viewer/injectables/click/click.js' },`

Thanks for pointing this out. It works, but it does not solve my problem. Event bubbling is limited to the current document, and cannot bubble up from an iFrame to the containing document.

The sample is fine to output something in the console, but i don't see how i can use that to trigger something in the document containing the reader.
