### ISSUE TITLE
disable storage?

### ISSUE THREAD

**Issue by gotson** [d-i-t-a/R2D2BC#628]
Hi,

there is an option to switch between local and session storage, but is it possible to opt-out entirely of settings storage ?

I want to manage settings storage myself, and i don't want the reader to store anything.

**Comment by patprache** [comment]
As far as I know, there are no options for doing this. I had to comment out lines 150 to 162 in src/reader.ts and add :

`   
const settingsStore = new MemoryStore();
const layerStore = new MemoryStore();
const annotator = new LocalAnnotator({ store: new MemoryStore() });
`

**Comment by gotson** [comment]
> As far as I know, there are no options for doing this. I had to comment out lines 150 to 162 in src/reader.ts and add :
> 
> ` const settingsStore = new MemoryStore(); const layerStore = new MemoryStore(); const annotator = new LocalAnnotator({ store: new MemoryStore() });`

I'm pulling the dep from npm, I would prefer to avoid having to publish my own forked package just for that.

Seems like it's a legit feature request then.

**Comment by gotson** [comment]
> As far as I know, there are no options for doing this. I had to comment out lines 150 to 162 in src/reader.ts and add :
> 
> ` const settingsStore = new MemoryStore(); const layerStore = new MemoryStore(); const annotator = new LocalAnnotator({ store: new MemoryStore() });`

I'm pulling the dep from npm, I would prefer to avoid having to publish my own forked package just for that.

Seems like it's a legit feature request then.

**Comment by aferditamuriqi** [comment]
@gotson i will have to better understand the scenario here, but assume we can add an option to not store, but there might be  more work to do than just comment out some code.

**Comment by gotson** [comment]
the scenario is that i want to be in charge of what is stored or not. I want the reader to be created in a pristine state everytime, and i don't want the reader to load some settings i am not aware of, or some position i am not aware of, from some storage i am not aware of.

**Comment by aferditamuriqi** [comment]
this has been resolved and it's merged
