### ISSUE TITLE
Detect resource at start/end?

### ISSUE THREAD

**Issue by gotson** [d-i-t-a/R2D2BC#639]
Hi,

i would like to detect whether the current resource is at start/end.

I've seen the following:

```
instance.addEventListener("resource.start", () => {
                console.log("listener start");
            });
instance.addEventListener("resource.end", () => {
                console.log("listener end");
            });
```

And:

```
api: {
                resourceAtStart: function() {
                    console.log("resourceAtStart");
                },
                resourceAtEnd: function() {
                    console.log("resourceAtEnd");
                },
```

The problem with the 2 above solutions is that the event is only triggered when the start/end of the resource is reached. It is however not triggered with a false value when the start/end is unreached.

For example, when scrolling all the way down, `resourceAtEnd` will be called. But if the user scrolls upwards a bit, there is no event.

IMHO the event should be called in 2 different scenarios:
- when the resource start/end is reached, with an argument of `true`
- when the resource start/end was previously reached, and is not reached anymore, with an argument of `false`

**Comment by aferditamuriqi** [comment]
this is by design, and has been implemented for example for buttons to be enabled or disabled when you reach the end or start, for everything else you have other apis that tell you which position you are at. i would rather not flood the apis with an argument of false. please look into another solution. unless you have a scenario which can't be covered. i would have to better understand the issue.

**Comment by gotson** [comment]
> this is by design, and has been implemented for example for buttons to be enabled or disabled when you reach the end or start, for everything else you have other apis that tell you which position you are at. i would rather not flood the apis with an argument of false. please look into another solution. unless you have a scenario which can't be covered. i would have to better understand the issue.

the problem i have with this is:
- if i use the built-in buttons, they get to appear/disappear correctly
- if i want to use the callbacks or event listeners, i don't have this functionality, because the calls are only made when true, but not when false

this is forcing me to use the built-in buttons, which are modified by html operations, and is not always compatible with virtual DOM frameworks like VueJS.

Ideally i would prefer that the reader allows to opt-out entirely of the required (and undocumented) html elemens / classes.

**Comment by aferditamuriqi** [comment]
@gotson let me find an implementation that used the api and surely not the sample buttons, and you can see how they implemented it, it's open source as well.
