### ISSUE TITLE
Cover is stretched vertically in scroll mode

### ISSUE THREAD

**Issue by gotson** [d-i-t-a/R2D2BC#660]
I noticed that quite often the book cover is stretched vertically when in scroll mode.

Scroll:
<img width="1460" alt="image" src="https://github.com/d-i-t-a/R2D2BC/assets/2139133/ec443568-3da7-4cbe-b492-a749d4ec5d44">

Paginated:
<img width="1458" alt="image" src="https://github.com/d-i-t-a/R2D2BC/assets/2139133/f4bf9cfa-93a9-41b3-8d5a-8b7a54d3de9d">

This happens with different books.

**Comment by aferditamuriqi** [comment]
@gotson we haven't seen this issue in any implementation so far, would be good to see the html and css of these books. 

example here 
<img width="2269" alt="Screenshot 2023-11-14 at 8 45 29 AM" src="https://github.com/d-i-t-a/R2D2BC/assets/17150623/be3d299f-f886-407b-b55b-582d55d1bf04">

**Comment by gotson** [comment]
Here is the book in question

[Many Lives, Many Masters_ The True Story o - Weiss, Brian L_.epub.zip](https://github.com/d-i-t-a/R2D2BC/files/13358905/Many.Lives.Many.Masters_.The.True.Story.o.-.Weiss.Brian.L_.epub.zip)

**Comment by aferditamuriqi** [comment]
Thank you @gotson i will test and evaluate the book.

**Comment by aferditamuriqi** [comment]
at first glance into it (not yet looked into the html and css of the book) it might seem that there is some css issue with the cover. i opened it in ibooks and this is what i see there 
<img width="1225" alt="Screenshot 2023-11-15 at 8 26 22 AM" src="https://github.com/d-i-t-a/R2D2BC/assets/17150623/6b7c4612-b851-41ce-9280-d182b646960d">

**Comment by gotson** [comment]
It works fine for me in Books on mac:
<img width="1454" alt="image" src="https://github.com/d-i-t-a/R2D2BC/assets/2139133/7d639794-99ea-49f5-a2da-1ecd28b7c927">

And on Thorium:
<img width="1463" alt="image" src="https://github.com/d-i-t-a/R2D2BC/assets/2139133/6d756301-86ab-4ad1-b550-b706a0e7977f">

**Comment by aferditamuriqi** [comment]
@gotson this is clearly a content issue

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="100%" height="100%" viewBox="0 0 719 1100" preserveAspectRatio="none">
                <image width="719" height="1100" xlink:href="images/00007.jpeg"></image>
            </svg>
```

if you change this 
`preserveAspectRatio="none" `
to 
`preserveAspectRatio="xMinYMid meet" `

or any other value that should be used. then this stretching would not happen. 

also we use readium css that is also injected into the reader, we don't apply any custom css here. therefore you are free to use in your implementation any change to the injected css. 

this is not considered an issue in R2D2BC, therefore closing this issue. 

<img width="1773" alt="Screenshot 2023-11-16 at 10 23 15 AM" src="https://github.com/d-i-t-a/R2D2BC/assets/17150623/52b521ea-f8c5-4bbf-ae5d-876291d26ea5">
